project:
  version: "0.0.1-SNAPSHOT"
validation:
  enabled: true

app:
  cors:
    allowedOrigins: https://crm.prmb2c-kizen.apps.dev-gen.delta.sbrf.ru, crm.prmb2c-kizen.apps.dev-gen.delta.sbrf.ru, https://ingress.prmb2c-kizen.apps.dev-gen.delta.sbrf.ru, ingress.prmb2c-kizen.apps.dev-gen.delta.sbrf.ru, prmb2c-kizen.apps.dev-gen.delta.sbrf.ru, https://tkldg-prm000001.vm.mos.cloud.sbrf.ru, tkldg-prm000001.vm.mos.cloud.sbrf.ru
    allowCredentials: true

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      base-path: /api/v1
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
server:
  port: ${SERVER_PORT:5002}
  compression:
    enabled: true
spring:
  application:
    name: spring-jpa-batch-insert
  profiles:
    active: local
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jmx:
    enabled: false
  liquibase:
    contexts: ${spring.profiles.active}
    enabled: true
  main:
    banner-mode: 'off'
springdoc:
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  swagger-ui:
    config-url: /api-docs/swagger-config
    disable-swagger-default-url: true
    path: /swagger-ui.html
    url: /api-docs
    use-root-path: true
