spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS AUTH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        database: h2
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                default_schema: psm_service_document
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
                generate_statistics: true
                order_inserts: true
                jdbc:
                    batch_size: 100
                    lob:
                        non_contextual_creation: true
        show-sql: true
    liquibase:
        change-log: classpath:db/db.changelog-master.xml
        default-schema: auth
        password: ''
        url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS AUTH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        user: sa
